import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Main_Heropage/Nav";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient" />
        </div>

        <main className="app">
          {/* Nav is neede dhere */}
          <Nav />
          {children}

          <Toaster />
        </main>
      </body>
    </html>
  );
}
